----
title: "r-wids-datathon"
author: "Emma Brooks"
date: "2023-09-27"
output: html_document
---

```{r load-package, include=FALSE}
library(tidyverse)
library(skimr)
library(caret)
library(mdsr)
library(GGally)
library(tree)
library(ISLR2)
library(randomForest)
library(recipes)
library(visdat)
library(workflows)
library(parsnip)
library(ranger)
library(vip)
library(robustHD)
```


```{r load-data}
train <- read_csv("/Users/ebrooks/Documents/thesis/project/r-wids-datathon/data/train.csv")
final_testing <- read_csv("/Users/ebrooks/Documents/thesis/project/r-wids-datathon/data/test.csv")
```

```{r summary, eval=FALSE}
ncol(train)
nrow(train)
colnames(train)
skim(train)
summary(final_testing)
```

```{r set-seed}
# set.seed(3911)
# inTrain <- createDataPartition(y = train$treatment_pd, p=0.7, list=FALSE)
# training <- train[inTrain,]
# testing <- train[-inTrain,]
#training_recipe <- recipe(treatment_pd ~., data = training)
```

```{r glimpse, eval=FALSE}
glimpse(training)

ncol(training)
nrow(training)
colnames(training)
skim(training)

# Rows = 19373
```

```{r nas, eval=FALSE}
training %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.))))

is.na(training)

# missing heat map
training %>%
  is.na() %>%
  reshape2::melt() %>%
  ggplot(aes(Var2, Var1, fill=value)) +
    geom_raster() +
  coord_flip() +
  scale_y_continuous(NULL, expand = c(0,0)) +
  scale_fill_grey(name = "",
                  labels = c("present",
                             "missing")) +
  xlab("observation") +
  theme(axis.text.y = element_text(size=4))

# missing visualization
vis_miss(training, cluster = TRUE, warn_large_data = FALSE)
```

```{r zero-variance-variables, eval=FALSE}
caret::nearZeroVar(training, saveMetrics = TRUE) %>%
  tibble::rownames_to_column() %>%
  filter(nzv)
```

```{r count, eval=FALSE}
training %>%
  na.omit() %>%
  summarize(across(everything(), min))

training %>%
  na.omit() %>%
  summarize(across(everything(), max))

training %>%
  select(patient_age) %>%
  arrange((patient_age))

training %>%
  count(patient_gender)

training %>%
  count(patient_state) %>%
  arrange(desc(n))

training %>% 
  select(metastatic_first_novel_treatment) %>%
  summary(NA) # 13243 NA's

training %>%
  count(metastatic_first_novel_treatment)

training %>% 
  select(metastatic_first_novel_treatment_type) %>%
  summary(NA)
training %>%
  count(metastatic_first_novel_treatment_type)

training %>% 
  select(bmi) %>%
  summary(NA)

training %>%
  count(bmi)

training %>% 
  select(patient_race) %>%
  summary(NA)

training %>%
  count(patient_race)

training %>% 
  select(metastatic_first_novel_treatment_type) %>%
  summary(NA)

training %>%
  count(metastatic_first_treatment_type)

training %>%
  count(breast_cancer_diagnosis_desc) %>%
  arrange(desc(n))

training %>%
  count(metastatic_cancer_diagnosis_code)

training %>%
  count(breast_cancer_diagnosis_year) %>%
  arrange(desc(n))
```
 
```{r wrangling-func}
wrangle <- function(data) {
  
  # remove variables with too many missing values
  data <- data %>%
    select(-c(metastatic_first_novel_treatment,
         metastatic_first_novel_treatment_type,
         patient_race,
         payer_type,
         bmi,
         metastatic_first_treatment_type,
         self_employed,
         farmer,
         patient_gender,
         # new
         patient_id, patient_state, division, patient_zip3,
         male, never_married, age_under_10, age_10_to_19, age_20s, age_30s, age_50s, age_60s, age_70s, age_over_80,
         income_household_median, income_household_under_5, income_household_5_to_10, income_household_10_to_15, income_household_15_to_20,
            income_household_20_to_25, income_household_25_to_35, income_household_35_to_50, income_household_50_to_75,
            income_household_100_to_150, income_household_150_over, income_household_six_figure,
            income_individual_median,
         housing_units, home_value,
         # could get rid of rent median instead of home value
         education_highschool, education_bachelors, education_graduate,
         limited_english, # 40 variables
         home_ownership, family_dual_income, race_other, race_multiple, disabled, # 34 variables
         divorced, widowed, density, race_white, rent_median, married, education_less_highschool, education_some_college, age_median, # 25 variables
         education_college_or_above, family_size, race_asian, poverty, veteran
         ))
  
  # making breast cancer diagnosis year categorical
  data$breast_cancer_diagnosis_year <- as.character(data$breast_cancer_diagnosis_year)
  
  # filter for 2016-2018
  # data <- data %>%
  #   filter(breast_cancer_diagnosis_year == "2017"|
  #          breast_cancer_diagnosis_year == "2018" |
  #          breast_cancer_diagnosis_year == "2016"  )
  
  
  # side variable
  finding_side <- data %>%
    select(breast_cancer_diagnosis_desc)

  finding_side <- deframe(finding_side)

  data <- data %>%
    mutate(breast_cancer_diagnosis_side = case_when(
      str_detect(finding_side, "left") ~ "left",
      str_detect(finding_side, "right") ~ "right",
      TRUE ~ "unspecified"
    ))
  
  data <- data %>%
    select(-c(breast_cancer_diagnosis_desc,
         breast_cancer_diagnosis_code))
  
  # body system variable
  data <- data %>%
    mutate(metastatic_cancer_body_system = case_when(
      metastatic_cancer_diagnosis_code %in% c("C770", "C771", "C772", "C773", "C774", "C775", "C778", "C779") ~ "lymphatic",
      metastatic_cancer_diagnosis_code %in% c("C7800", "C7801", "C7802", "C781", "C782", "C7839") ~ "respiratory",
      metastatic_cancer_diagnosis_code %in% c("C784", "C785", "C786", "C787", "C7889") ~ "digestive",
      metastatic_cancer_diagnosis_code %in% c("C7900", "C7901", "C7902", "C7910") ~ "urinary",
      metastatic_cancer_diagnosis_code %in% c("C792", "C7931", "C7932", "C7940", "C7949") ~ "nervous",
      metastatic_cancer_diagnosis_code %in% c("C7951", "C7952") ~ "skeletal",
      metastatic_cancer_diagnosis_code %in% c("C7960", "C7961", "C7962", "C7981", "C7982") ~ "reproductive",
      metastatic_cancer_diagnosis_code %in% c("C7970", "C7971", "C7972") ~ "adrenal glands",
      metastatic_cancer_diagnosis_code %in% c("C7989", "C799") ~ "other",
    ))
  
  data <- data %>%
    select(-metastatic_cancer_diagnosis_code)
  
  data <- data %>%
    select(-metastatic_first_treatment)
  
  #data <- na.omit(data)
  data$treatment_pd <- winsorize(data$treatment_pd, probs = 0.05)
  
  data$breast_cancer_diagnosis_year <- as.factor(data$breast_cancer_diagnosis_year)
  data$breast_cancer_diagnosis_side <- as.factor(data$breast_cancer_diagnosis_side)
  data$region <- as.factor(data$region)
  data$metastatic_cancer_body_system <- as.factor(data$metastatic_cancer_body_system)

  return(data)
}

train <- wrangle(train)

# splitting 
set.seed(3911)
inTrain <- createDataPartition(y = train$treatment_pd, p=0.7, list=FALSE)
training <- train[inTrain,]
testing <- train[-inTrain,]

#training <- wrangle(training)
#testing <- wrangle(testing)

# imputing
training <- na.roughfix(training)
testing <- na.roughfix(testing)

#training$treatment_pd <- winsorize(training$treatment_pd, probs = c(0.05, 0.95))
#training$treatment_pd <- winsor(training$treatment_pd, trim = 0.05)
#testing$treatment_pd <- winsor(testing$treatment_pd, trim = 0.05)

```

```{r submission-wrangle}
submission_wrangle <- function(data) {
  
  # remove variables with too many missing values
  data <- data %>%
    select(-c(metastatic_first_novel_treatment,
         metastatic_first_novel_treatment_type,
         patient_race,
         payer_type,
         bmi,
         metastatic_first_treatment_type,
         self_employed,
         farmer,
         patient_gender,
         # new
         patient_state, division, patient_zip3,
         male, never_married, age_under_10, age_10_to_19, age_20s, age_30s, age_50s, age_60s, age_70s, age_over_80,
         income_household_median, income_household_under_5, income_household_5_to_10, income_household_10_to_15, income_household_15_to_20,
            income_household_20_to_25, income_household_25_to_35, income_household_35_to_50, income_household_50_to_75,
            income_household_100_to_150, income_household_150_over, income_household_six_figure,
            income_individual_median,
         housing_units, home_value,
         # could get rid of rent median instead of home value
         education_highschool, education_bachelors, education_graduate,
         limited_english, # 40 variables
         home_ownership, family_dual_income, race_other, race_multiple, disabled, # 34 variables
         divorced, widowed, density, race_white, rent_median, married, education_less_highschool, education_some_college, age_median, # 25 variables
         education_college_or_above, family_size, race_asian, poverty, veteran
         ))
  
  # making breast cancer diagnosis year categorical
  data$breast_cancer_diagnosis_year <- as.character(data$breast_cancer_diagnosis_year)
  
  # side variable
  finding_side <- data %>%
    select(breast_cancer_diagnosis_desc)

  finding_side <- deframe(finding_side)

  data <- data %>%
    mutate(breast_cancer_diagnosis_side = case_when(
      str_detect(finding_side, "left") ~ "left",
      str_detect(finding_side, "right") ~ "right",
      TRUE ~ "unspecified"
    ))
  
  data <- data %>%
    select(-c(breast_cancer_diagnosis_desc,
         breast_cancer_diagnosis_code))
  
  # body system variable
  data <- data %>%
    mutate(metastatic_cancer_body_system = case_when(
      metastatic_cancer_diagnosis_code %in% c("C770", "C771", "C772", "C773", "C774", "C775", "C778", "C779") ~ "lymphatic",
      metastatic_cancer_diagnosis_code %in% c("C7800", "C7801", "C7802", "C781", "C782", "C7839") ~ "respiratory",
      metastatic_cancer_diagnosis_code %in% c("C784", "C785", "C786", "C787", "C7889") ~ "digestive",
      metastatic_cancer_diagnosis_code %in% c("C7900", "C7901", "C7902", "C7910") ~ "urinary",
      metastatic_cancer_diagnosis_code %in% c("C792", "C7931", "C7932", "C7940", "C7949") ~ "nervous",
      metastatic_cancer_diagnosis_code %in% c("C7951", "C7952") ~ "skeletal",
      metastatic_cancer_diagnosis_code %in% c("C7960", "C7961", "C7962", "C7981", "C7982") ~ "reproductive",
      metastatic_cancer_diagnosis_code %in% c("C7970", "C7971", "C7972") ~ "adrenal glands",
      metastatic_cancer_diagnosis_code %in% c("C7989", "C799") ~ "other",
    ))
  
  data <- data %>%
    select(-metastatic_cancer_diagnosis_code)
  
  data <- data %>%
    select(-metastatic_first_treatment)
  
  data$breast_cancer_diagnosis_year <- as.factor(data$breast_cancer_diagnosis_year)
  data$breast_cancer_diagnosis_side <- as.factor(data$breast_cancer_diagnosis_side)
  data$region <- as.factor(data$region)
  data$metastatic_cancer_body_system <- as.factor(data$metastatic_cancer_body_system)

  return(data)
}

# for submission
final_testing <- submission_wrangle(final_testing)
final_patientid <- final_testing %>% select(patient_id)
final_testing <- final_testing %>% select(-patient_id)

# impute
final_testing <- na.roughfix(final_testing)
```

```{check, eval = FALSE}
training %>%
  ggplot(aes(x = treatment_pd)) +
  geom_boxplot()

summary(training$treatment_pd)

training %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.))))

quantile(training$treatment_pd, probs = c(0.05, 0.95))
quantile(training$treatment_pd, probs = c(0.05, 0.81))
```

```{r lm-data, eval=FALSE}
lm_wrangle <- function(data) {
  
  # remove variables with too many missing values
  data <- data %>%
    select(-c(metastatic_first_novel_treatment,
         metastatic_first_novel_treatment_type,
         patient_race,
         payer_type,
         bmi,
         metastatic_first_treatment_type,
         self_employed,
         farmer,
         patient_gender,
         # new
         patient_id, patient_state, division, patient_zip3,
         male, never_married, age_under_10, age_10_to_19, age_20s, age_30s, age_50s, age_60s, age_70s, age_over_80,
         income_household_median, income_household_under_5, income_household_5_to_10, income_household_10_to_15, income_household_15_to_20,
            income_household_20_to_25, income_household_25_to_35, income_household_35_to_50, income_household_50_to_75,
            income_household_100_to_150, income_household_150_over, income_household_six_figure,
            income_individual_median,
         housing_units, home_value,
         # could get rid of rent median instead of home value
         education_highschool, education_bachelors, education_graduate,
         limited_english, # 40 variables
         home_ownership, family_dual_income, race_other, race_multiple, disabled, # 34 variables
         divorced, widowed, density, race_white, rent_median, married, education_less_highschool, education_some_college, age_median, # 25 variables
         education_college_or_above, family_size, race_asian, poverty, veteran
         ))
  
  # making breast cancer diagnosis year categorical
  data$breast_cancer_diagnosis_year <- as.character(data$breast_cancer_diagnosis_year)
  
  # filter for 2016-2018
   # data <- data %>%
   #   filter(breast_cancer_diagnosis_year == "2018" |
   #            breast_cancer_diagnosis_year == "2017" |
   #            breast_cancer_diagnosis_year == "2016")

   # data <- data %>%
   #  select(-breast_cancer_diagnosis_year)
  
  # side variable
  finding_side <- data %>%
    select(breast_cancer_diagnosis_desc)

  finding_side <- deframe(finding_side)

  data <- data %>%
    mutate(breast_cancer_diagnosis_side = case_when(
      str_detect(finding_side, "left") ~ "left",
      str_detect(finding_side, "right") ~ "right",
      TRUE ~ "unspecified"
    ))
  
  data <- data %>%
    select(-c(breast_cancer_diagnosis_desc,
         breast_cancer_diagnosis_code))
  
  # body system variable
  data <- data %>%
    mutate(metastatic_cancer_body_system = case_when(
      metastatic_cancer_diagnosis_code %in% c("C770", "C771", "C772", "C773", "C774", "C775", "C778", "C779") ~ "lymphatic",
      metastatic_cancer_diagnosis_code %in% c("C7800", "C7801", "C7802", "C781", "C782", "C7839") ~ "respiratory",
      metastatic_cancer_diagnosis_code %in% c("C784", "C785", "C786", "C787", "C7889") ~ "digestive",
      metastatic_cancer_diagnosis_code %in% c("C7900", "C7901", "C7902", "C7910") ~ "urinary",
      metastatic_cancer_diagnosis_code %in% c("C792", "C7931", "C7932", "C7940", "C7949") ~ "nervous",
      metastatic_cancer_diagnosis_code %in% c("C7951", "C7952") ~ "skeletal",
      metastatic_cancer_diagnosis_code %in% c("C7960", "C7961", "C7962", "C7981", "C7982") ~ "reproductive",
      metastatic_cancer_diagnosis_code %in% c("C7970", "C7971", "C7972") ~ "adrenal glands",
      metastatic_cancer_diagnosis_code %in% c("C7989", "C799") ~ "other",
    ))
  
  data <- data %>%
    select(-metastatic_cancer_diagnosis_code)
  
  data <- data %>%
    select(-metastatic_first_treatment)
  
    data <- data %>%
      mutate(log_treatment_pd = log(treatment_pd))

    data <- data %>%
      mutate(log_treatment_pd = log(treatment_pd + 0.001), .keep = "all")

    data <- data %>%
      select(-treatment_pd)
    
  data <- na.omit(data)
  return(data)
}

lm_training <- lm_wrangle(training)
lm_testing <- lm_wrangle(testing)

```

```{r count2, eval=FALSE}
training %>%
  count(breast_cancer_diagnosis_code) %>%
  arrange(desc(n))

training %>%
  count(metastatic_cancer_diagnosis_code) %>%
  arrange(desc(n))

training %>%
  count(metastatic_first_treatment) 
```

```{r correlation-heat-map, eval=FALSE}
numeric_training <- training %>% select(male, female, married, divorced, never_married, widowed, race_white, race_black)
#numeric_training <- select_if(training, is.numeric)
numeric_training <- numeric_training %>% mutate(patient_id = NULL,
                           patient_zip3 = NULL,
                           breast_cancer_diagnosis_year = NULL)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))

# highly correlated variables 
# married, never married -- -1
# married, race black -- ~-0.6
# never married, race white -- ~0.7


# get rid of 
# male
# never married

# age
numeric_training <- training %>% select(age_median, age_under_10, age_10_to_19, age_20s, age_30s, age_40s, age_50s, age_60s, age_70s, age_over_80)
numeric_training <- numeric_training %>% mutate(patient_id = NULL,
                           patient_zip3 = NULL,
                           breast_cancer_diagnosis_year = NULL)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))

# get rid of 
# everything except age median and age 40s

# income
numeric_training <- training %>% select(income_household_median, income_household_under_5, income_household_5_to_10, income_household_10_to_15, income_household_15_to_20, income_household_20_to_25, income_household_25_to_35, income_household_35_to_50, income_household_50_to_75, income_household_75_to_100, income_household_100_to_150, income_household_150_over, income_household_six_figure, income_individual_median)
numeric_training <- numeric_training %>% mutate(patient_id = NULL,
                           patient_zip3 = NULL,
                           breast_cancer_diagnosis_year = NULL)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))

# getting rid of -- all but income 75-100

# housing
numeric_training <- training %>% select(home_ownership, housing_units, home_value, rent_median, rent_burden)
numeric_training <- numeric_training %>% mutate(patient_id = NULL,
                           patient_zip3 = NULL,
                           breast_cancer_diagnosis_year = NULL)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))

# gerting rid of housing units, rent median

# education
numeric_training <- training %>% select(education_less_highschool, education_highschool, education_some_college, education_bachelors, education_graduate, education_college_or_above, education_stem_degree, labor_force_participation, unemployment_rate)
numeric_training <- numeric_training %>% mutate(patient_id = NULL,
                           patient_zip3 = NULL,
                           breast_cancer_diagnosis_year = NULL)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))

# getting rid of edu highschool, bachelors, graduate, college or above

# race
numeric_training <- training %>% select(race_white, race_black, race_asian, race_native, race_pacific, race_other, race_multiple)
numeric_training <- numeric_training %>% mutate(patient_id = NULL,
                           patient_zip3 = NULL,
                           breast_cancer_diagnosis_year = NULL)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))

# other
numeric_training <- training %>% select(hispanic, disabled, poverty, limited_english, commute_time, health_uninsured, veteran)
numeric_training <- numeric_training %>% mutate(patient_id = NULL,
                           patient_zip3 = NULL,
                           breast_cancer_diagnosis_year = NULL)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))

# lm data

# lm_training <- lm_training %>% select(-c(population, married, family_dual_income, disabled, poverty, home_ownership, limited_english, race_other,
#                                          labor_force_participation, race_asian, race_white, veteran, education_less_highschool, age_median,
#                                          income_household_5_to_10, home_value, density,
#                                          family_size, unemployment_rate, education_some_college, commute_time,
#                                          widowed, education_stem_degree))

numeric_training <- select_if(lm_training, is.numeric)
numeric_training <- numeric_training %>% mutate(patient_id = NULL,
                           patient_zip3 = NULL,
                           breast_cancer_diagnosis_year = NULL)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))

numeric_training <- select_if(training, is.numeric)
numeric_training <- na.omit(numeric_training)
corrplot::corrplot(cor(numeric_training))
```

```{r, eval=FALSE}
lm_training %>%
  select_if(is.character)

lm_training %>%
  count(division)

lm_training %>%
  count(metastatic_cancer_body_system)
```

```{r zero-var-check, eval=FALSE}
skim(training)

caret::nearZeroVar(training, saveMetrics = TRUE) %>%
  tibble::rownames_to_column() %>%
  filter(nzv)
```

## Distributions
```{r response-dist}
# treatment pd -- very right skewed
training %>%
  ggplot(mapping = aes(x = treatment_pd)) +
          geom_boxplot() +
  labs(title = "Distribution of Treatment Period",
       x = "Days") +
  theme(axis.ticks.y = element_blank(),
        axis.text.y = element_blank())

training %>%
  ggplot(mapping = aes(x = treatment_pd)) + 
  geom_histogram() + 
  labs(title = "Distribution of Treatment Period",
       x = "Days")

training %>%
  filter(treatment_pd < 200) %>%
  ggplot(mapping = aes(x = treatment_pd)) +
          geom_boxplot()

summary(training$treatment_pd)
# min = 0
# 1q = 36
# median = 70
# mean = 134.3
# 3q = 132
# max = 1446

# without 2015
# min = 0 
# 1q = 32
# median = 59.50
# mean = 88.26
# 3q = 98
# max = 1046

# log transformation
# log_treatment_pd <- log(training$treatment_pd)

#training %>%
#  summary(log_treatment_pd)

# log boxplot
#training %>%
#  ggplot(mapping = aes(x = log_treatment_pd)) +
#          geom_boxplot() 

```

```{r recipe-normalization-standardization, eval = FALSE}
# recipe package log
#training_recipe <- recipe(treatment_pd ~., data = training) %>%
#  step_log(all_outcomes())

#training_recipe

# YeoJohnson -- note = can do this with preProc func
training_recipe <- recipe(treatment_pd ~., data = training) %>%
  step_nzv(all_predictors()) %>%
  step_YeoJohnson(all_numeric_predictors()) %>%
  step_YeoJohnson(all_outcomes()) %>%
  step_center(all_numeric_predictors()) %>%
  step_scale(all_numeric_predictors()) %>%
  update_role(treatment_pd, new_role = "outcome") 
  
training_recipe

testing_recipe <- recipe(treatment_pd ~., data = testing) %>%
  step_nzv(all_predictors()) %>%
  step_YeoJohnson(all_numeric_predictors()) %>%
  step_YeoJohnson(all_outcomes()) %>%
  step_center(all_numeric_predictors()) %>%
  step_scale(all_numeric_predictors())  %>%
  update_role(treatment_pd, new_role = "outcome")

testing_recipe
```

```{r distributions, eval = FALSE}
# region
training %>%
  ggplot(mapping = aes(x = region)) +
          geom_bar()

# divisiom
training %>%
  ggplot(mapping = aes(y = division)) +
          geom_bar()

# density -- very right skewed
training %>%
  filter(density <= 10000) %>%
  ggplot(mapping = aes(x = density)) +
          geom_boxplot()

# female -- normal
training %>%
  ggplot(mapping = aes(x = female)) +
          geom_boxplot()

# health uninsured -- little right skewed
training %>%
  ggplot(mapping = aes(x = health_uninsured)) +
          geom_boxplot()

# race white -- little left skewed
training %>%
  ggplot(mapping = aes(x = race_white)) +
          geom_boxplot()

# limited english -- right skewed
training %>%
  filter(limited_english < 40) %>%
  ggplot(mapping = aes(x = limited_english)) +
          geom_boxplot()
```

```{r income-distributions, eval = FALSE}
# income household median
training %>%
  ggplot(mapping = aes(x = income_household_median)) +
          geom_boxplot()

# home ownership -- left skewed
training %>%
  ggplot(mapping = aes(x = home_ownership)) +
          geom_boxplot()

# rent burden -- somewhat normal, a little right skewed
training %>%
  filter(rent_burden < 70) %>%
  ggplot(mapping = aes(x = rent_burden)) +
          geom_boxplot()

# education high school -- normal
training %>%
  ggplot(mapping = aes(x = education_highschool)) +
          geom_boxplot()

# unemployment rate -- right skewed
training %>%
  ggplot(mapping = aes(x = unemployment_rate)) +
          geom_boxplot()

# poverty -- right skewed
training %>%
  ggplot(mapping = aes(x = poverty)) +
          geom_boxplot()

#training %>%
#  ggplot(mapping = aes(x = breast_cancer_diagnosis_side, y = log_treatment_pd)) + # had log treatment pd here
#          geom_boxplot()
```

## Scatterplots
```{r scatter-treatment-region, eval=FALSE}
# colored by region

# patient age
ggplot(data = training, mapping = aes(x = patient_age, y = treatment_pd, color=region)) +
           geom_point()

# median income household for zip code
# more south in lower income median
ggplot(data = training, mapping = aes(x = income_household_median, y = treatment_pd, color=region)) +
           geom_point()

# population for zip code
# outliers are in northeast, more midwest in lower population 
ggplot(data = training, mapping = aes(x = population, y = treatment_pd, color=region)) +
           geom_point()

# median age for zip code
ggplot(data = training, mapping = aes(x = age_median, y = treatment_pd, color=region)) +
           geom_point()

# unemployement rate for zip code
# 
ggplot(data = training, mapping = aes(x = unemployment_rate, y = treatment_pd, color=region)) +
           geom_point()

# patient age for zip code 
ggplot(data = training, mapping = aes(x = patient_age, y = treatment_pd, color=region)) +
           geom_point()
```

```{r scatter-treatment-breast-side, eval = FALSE}
# all of them -- unspecified more with higher treatment period

# patient age
ggplot(data = training, mapping = aes(x = patient_age, y = treatment_pd, color= breast_cancer_diagnosis_side)) +
           geom_point()

# median income household for zip code
ggplot(data = training, mapping = aes(x = income_household_median, y = treatment_pd, color= breast_cancer_diagnosis_side)) +
           geom_point()

# population for zip code
ggplot(data = training, mapping = aes(x = population, y = treatment_pd, color= breast_cancer_diagnosis_side)) +
           geom_point()

# median age for zip code
ggplot(data = training, mapping = aes(x = age_median, y = treatment_pd, color= breast_cancer_diagnosis_side)) +
           geom_point()

# unemployement rate for zip code
ggplot(data = training, mapping = aes(x = unemployment_rate, y = treatment_pd, color= breast_cancer_diagnosis_side)) +
           geom_point()

# patient age for zip code 
ggplot(data = training, mapping = aes(x = patient_age, y = treatment_pd, color= breast_cancer_diagnosis_side)) +
           geom_point()

```

```{r scatter-treatment-body-system, eval=FALSE}
# all -- lymphatic areas are more around shorter treatment periods

# patient age
ggplot(data = training, mapping = aes(x = patient_age, y = treatment_pd, color= metastatic_cancer_body_system)) +
           geom_point()

# median income household for zip code
ggplot(data = training, mapping = aes(x = income_household_median, y = treatment_pd, color= metastatic_cancer_body_system)) +
           geom_point()

# population for zip code
ggplot(data = training, mapping = aes(x = population, y = treatment_pd, color= metastatic_cancer_body_system)) +
           geom_point()

# median age for zip code
ggplot(data = training, mapping = aes(x = age_median, y = treatment_pd, color= metastatic_cancer_body_system)) +
           geom_point()

# unemployement rate for zip code
ggplot(data = training, mapping = aes(x = unemployment_rate, y = treatment_pd, color= metastatic_cancer_body_system)) +
           geom_point()

# patient age for zip code 
ggplot(data = training, mapping = aes(x = patient_age, y = treatment_pd, color= metastatic_cancer_body_system)) +
           geom_point(alpha = 0.4)
```

## Final Visualizations
```{r final-viz}
# patient age -- pretty normal
training %>%
  ggplot(mapping = aes(x = patient_age)) +
          geom_boxplot() +
          labs(x = "Age (Years)",
               title = "Distribution of Patient Age")

# treatment pd distribution -- filtered
training %>%
  filter(treatment_pd < 500) %>%
  ggplot(mapping = aes(x = treatment_pd)) +
          geom_boxplot() +
          labs(x = "Treatment Period (days)",
               title = "Distribution of Period Between Diagnosis and Treatment",
               subtitle = "For less than 500 days")


# body system by treatment pd -- filtered
training %>%
  ggplot(mapping = aes(y = metastatic_cancer_body_system, x = treatment_pd)) +
  geom_boxplot() +
  labs(x = "Treatment Period (days)",
       y = "",
       title = "Distribution of Treatment Period by Metastatic Body System",
       subtitle = "Winsorized Treatment Period")

# diagnosis year bar chart
training %>%
  ggplot(aes(x = breast_cancer_diagnosis_year, fill = breast_cancer_diagnosis_side)) +
  geom_bar() +
  labs(title = "Count of Breast Cancer Diagnoses by Year",
       x = "Year",
       y = "Number of Patients",
       fill = "Side",
       subtitle = "Colored by Breast Diagnosis Side")

# boxplot - year by treatment period
training %>%
  ggplot(aes(x = treatment_pd, y = breast_cancer_diagnosis_year)) +
  geom_boxplot() +
  labs(x = " Treatment Period (Days)",
       y = "",
       title = "Treatment Period by Diagnosis Year",
       subtitle = "Winsorized Treatment Period")


# diagnosis year with metastatic body system
training %>%
  ggplot(aes(x = breast_cancer_diagnosis_year, fill = metastatic_cancer_body_system)) +
  geom_bar() +
  labs(title = "Count of Breast Cancer Diagnoses by Year",
       subtitle = "Colored with Metastatic Body System",
       x = "Year",
       y = "Number of Patients",
       fill = "Body System")
```

```{r colinearity, eval=FALSE}
lm_training %>% 
  select(-c(patient_state, patient_zip3, patient_id, treatment_pd)) %>%
  select(patient_age:density) %>%
  ggpairs()
```

```{r lin-mod, eval=FALSE}
# lm
training_lm1 <- train(log_treatment_pd ~ ., 
                     data = lm_training,
                     method = "lm",
                     preProc = c("center", "scale", "YeoJohnson"))

pred <- predict(training_lm2, lm_testing)
y <- exp(lm_testing$log_treatment_pd)
y.pred <- exp(pred)

# rmse
sqrt(mean((y - y.pred)^2))



# forward selection
training_lm2 <- train(log_treatment_pd ~ ., 
                     data = lm_training,
                     method = "leapBackward",
                     preProc = c("center", "scale", "YeoJohnson"))

pred <- predict(training_lm2, lm_testing)
y <- exp(lm_testing$log_treatment_pd)
y.pred <- exp(pred)

# rmse
sqrt(mean((y - y.pred)^2))

summary(training_lm1)
summary(training_lm2)


# manual forward selection
training_lm2 <- train(log_treatment_pd ~ breast_cancer_diagnosis_year + breast_cancer_diagnosis_side +
                        metastatic_cancer_body_system ,  
                     data = lm_training,
                     method = "leapForward",
                     preProc = c("center", "scale", "YeoJohnson"))

pred <- predict(training_lm2, lm_testing)
y <- exp(lm_testing$log_treatment_pd)
y.pred <- exp(pred)

# rmse
sqrt(mean((y - y.pred)^2))


# step function -- backward
slm <- lm(log_treatment_pd ~., lm_training)
slm1 <- stats::step(slm, direction="backward")

#rmse
pred <- predict(slm1, lm_testing)
y <- exp(lm_testing$log_treatment_pd)
y.pred <- exp(pred)
sqrt(mean((y - y.pred)^2))

slm1 %>%
  tidy() %>%
  select(term, estimate) %>%
  mutate(estimate_exp = exp(estimate))

# Step:  AIC=12028.55
# log_treatment_pd ~ patient_age + breast_cancer_diagnosis_year + 
#     region + income_household_75_to_100 + rent_burden + labor_force_participation + 
#     race_black + hispanic + commute_time + health_uninsured + 
#     breast_cancer_diagnosis_side + metastatic_cancer_body_system

# RMSE = 111.5587

# 2017-2018
# Step:  AIC=7676.92
# log_treatment_pd ~ patient_age + breast_cancer_diagnosis_year + 
#     region + income_household_75_to_100 + rent_burden + labor_force_participation + 
#     race_black + hispanic + health_uninsured + metastatic_cancer_body_system
# RMSE = 83.2735

# 2018
# Step:  AIC=3139.39
# log_treatment_pd ~ patient_age + population + female + race_black + 
#     hispanic + health_uninsured + metastatic_cancer_body_system
# RMSE =  53.57248
```

```{r tree, eval=FALSE}
# na's
#training %>%
#  select(everything()) %>%
#  summarise_all(funs(sum(is.na(.))))


# # 10 fold cv by default
# training_tree <- rpart(
#   formula = treatment_pd ~.,
#   data = training,
#   preProc = c("center", "scale", "YeoJohnson"),
#   method = "anova" # anova bc of regression tree (HoML DT)
# )
# rpart.plot(training_tree)

# caret way
training_tree2 <- train(treatment_pd ~.,
                        data = training,
                        method = "rpart",
                        preProc = c("center", "scale"),
                        metric = "RMSE")

pred <- predict(training_tree2, testing)

# rmse
sqrt(mean((testing$treatment_pd - pred)^2))

# rmse(preds = pred, actuals = )
```

```{r forest, eval=FALSE}
# # train function tree
# training_forest <- train(treatment_pd ~.,
#                          data = training,
#                          method = "rf",
#                          trControl = trainControl(method = "cv", number = 10),
#                          preProc = c("center", "scale", "YeoJohnson"),
#                          metric = "RMSE")
# 
# # random forest 1
# pred <- predict(training_forest2, testing)


# rand forest ranger tree
tf_mod <- rand_forest(
            mtry = 2,
            trees = 5000
          )

training_forest2 <- tf_mod %>%
                    set_engine("ranger") %>%
                    set_mode("regression") %>%
                    fit(treatment_pd ~ ., training)

pred <- predict(training_forest2, testing)

sqrt(mean((testing$treatment_pd - pred$.pred)^2))

# testing for submission

test_forest <- randomForest(treatment_pd ~., training, ntree = 1200, mtry = 2)
test_pred <- predict(test_forest, testing)
sqrt(mean((testing$treatment_pd - test_pred)^2))
summary(test_pred)

test_testing <- bind_cols(test_patientid, test_pred)
colnames(test_testing)[2] <- "treatment_pd"
test_testing %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.))))

```

```{r submission-forest}
# submission forest
submission_forest <- randomForest(treatment_pd ~., training, ntree = 1200, mtry = 2)
final_pred <- predict(submission_forest, final_testing)
summary(final_pred)

final_testing <- bind_cols(final_patientid, final_pred)
colnames(final_testing)[2] <- "treatment_pd"
final_testing %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.))))

write_csv(final_testing, "/Users/ebrooks/Documents/thesis/project/r-wids-datathon/data/submission.csv")
read_csv("/Users/ebrooks/Documents/thesis/project/r-wids-datathon/data/submission.csv")
```

```{r importance-viz, eval=FALSE}
rf_impurity <- ranger(
  formula = treatment_pd ~.,
  data = training,
  num.trees = 500,
  mtry = 2,
  min.node.size = 1,
  sample.fraction = .70,
  replace = FALSE,
  importance = "impurity",
  respect.unordered.factors = "order",
  verbose = FALSE,
  seed = 3911
)

rf_permutation <- ranger(
  formula = treatment_pd ~.,
  data = training,
  num.trees = 500,
  mtry = 2,
  min.node.size = 1,
  sample.fraction = .70,
  replace = FALSE,
  importance = "permutation",
  respect.unordered.factors = "order",
  verbose = FALSE,
  seed = 3911
)

p1 <- vip::vip(rf_impurity, num_features = 5, bar = FALSE)
p2 <- vip::vip(rf_permutation, num_features = 5, bar = FALSE)

gridExtra::grid.arrange(p1, nrow = 1)
gridExtra::grid.arrange(p2, nrow = 1)
```

```{r recipe-forest, eval=FALSE}
training_rec_forest <- rand_forest(
                          mode = "regression",
                          engine = "randomForest"
                        )

training_workflow <- 
  workflow() %>%
  add_model(training_rec_forest) %>%
  add_recipe(training_recipe)

training_workflow

training_fit <-
  training_workflow %>%
  fit(data = training)

predict(training_fit, new_data = testing)
```

